name: 'Run Project Validation'
description: 'Run all validations for project'

inputs:
  godot-version:
    description: 'The version of Godot to run validation with'
    required: true
    default: 0.0
  godot-executable:
    description: 'The path to the Godot executable'
    required: false
    default: /Applications/Godot.app/Contents/MacOS/Godot

runs:
  using: 'composite'
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v3

    - name: Install Godot
      shell: bash
      run: |
        curl -o ./godot.zip "https://downloads.tuxfamily.org/godotengine/${{ inputs.godot-version }}/Godot_v${{ inputs.godot-version }}-stable_macos.universal.zip"
        unzip ./godot.zip
        mv ./Godot.app /Applications/Godot.app

    - name: Open Godot for reimport
      shell: bash
      run: ${{ inputs.godot-executable }} --editor --headless --quit || true

    - name: Run project validations
      shell: bash
      run: ${{ inputs.godot-executable }} --script scripts/run_validations.gd --headless
