name: 'Tag Version'
description: 'Tag the latest commit with its semantic version'

inputs:
  version-file:
    description: 'The file containing the version number'
    required: true
    default: 'undefined'
  version-regex:
    description: 'The regex expression to capture the semantic version'
    required: true
    default: '[0-9.\-A-z]*'

runs:
  using: 'composite'
  steps:
    - name: Checkout current branch
      uses: actions/checkout@v3
    
    - name: Assign version string
      shell: bash
      run: |
        VERSION=`grep -Po "${{ inputs.version-file }}" ${{ inputs.version-regex }}`
        echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT
      id: branch

    - name: Tag latest version
      uses: negz/create-tag@v1
      with:
        version: ${{ steps.branch.outputs.VERSION }}
        token: ${{ secrets.PUBLIC_REPO_TOKEN }}