name: Build
on:
   push:
     branches: [ master ]

   pull_request:
     branches: [ master feature/godot-4 ]

   workflow_dispatch:

 jobs:
   build:
     runs-on: macos-latest
     env:
       OUTPUT_DIR: output/macos
       OUTPUT_NAME: RNGStronghold
       GODOT_VERSION: 4.0.2
       GODOT_TEMPLATES_DIR: "/Users/runner/Library/Application Support/Godot/templates"

     steps:
     - uses: actions/checkout@v2

     - name: install godot
       run: brew install godot

     - name: Download Godot templates
       run: curl -o ./godot-templates.zip "https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz"

     - name: Setup templates
       run: unzip ./godot-templates.zip -d "$GODOT_TEMPLATES_DIR/$GODOT_VERSION.stable"

     - name: build project
       run: |
            mkdir -p $OUTPUT_DIR
            godot --export-debug macOS --headless

     - uses: actions/upload-artifact@v3
       with:
         name: macOS Build
         path: $OUTPUT_DIR/$OUTPUT_NAME.app
