name: Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Godot
        run: brew install godot

      - name: Setup Godot templates
        run: |
          curl -o ./godot-templates.zip "https://downloads.tuxfamily.org/godotengine/$GODOT_VERSION/Godot_v$GODOT_VERSION-stable_export_templates.tpz"
          unzip ./godot-templates.zip -d "$GODOT_TEMPLATES_DIR/$GODOT_VERSION.stable"
        
      - name: Build application
        run: |
          mkdir -p $OUTPUT_DIR
          godot --export-debug macOS --headless
      
      - uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: macOS Build
          # A file, directory or wildcard pattern that describes what to upload
          path: $OUTPUT_DIR/$OUTPUT_NAME.app