name: macOS

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: install godot
      run: brew install godot
