name: Tag

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:

env:
  VERSION_FILE: project.godot
  VERSION_REGEX: config\/version=\"\K[0-9.\-A-z]*

jobs:
  tag-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
      
      - name: Assign version string
        run: |
          VERSION=`grep -Po "${{ env.VERSION_REGEX }}" ${{ env.VERSION_FILE }}`
          echo "VERSION=v$VERSION" >> $GITHUB_OUTPUT
        id: branch

      - name: Tag latest version
        uses: negz/create-tag@v1
        with:
          version: ${{ steps.branch.outputs.VERSION }}
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
